local constM = {}

constM.PHYS_FOLD = "PhysicsFolder"
constM.BALL_FOLD = "BallFolder"
constM.COF_NAME = "PhysicsObjectFolders"

constM.START_LEVEL = "Lobby Planet"

constM.CAM_DIST = 32.5
constM.CAM_Y_OFFSET = 1.5
constM.CAM_X_BOUNDARY = 0.0

constM.MIN_GRAV_DIST = 12.5
constM.GRAV_POWER = 6.5
constM.GRAV_SPEED_CAP = 50.0
constM.REGEN_MAGNI = 0.2
constM.GRAV_MAX_TIME = 4
constM.GRAV_REG_COOLDOWN = 0.76

constM.DEFAULT_GRAVITY = Vector3.New(0, -85.5, 0)
constM.DEFAULT_SUNLIGHT_COLOR = Color.FromHex("#ff7c6f")

constM.DEFAULT_BALL_COLOR = Color.FromHex("#0096ff")

return constM